#!/bin/bash
# ruTorrent e(x)tras management
#
# SERVIDOR HD

function _intro() {
  whiptail --title "ruTorrent Extras" --msgbox "Bienvenido a rtx! Aquí puedes instalar o borrar plugins y temas para ruTorrent. Múevete con las flechas, barra espaciadora para seleccionar y enter para continuar." 15 50
}

function _function() {
  function=$(whiptail --title "rtx" --menu "Choose an option:" --ok-button "Continue" --nocancel 12 50 3 \
               Plugins "" \
               Themes "" \
               Exit "" 3>&1 1>&2 2>&3)

    if [[ $function == Plugins ]]; then
      _plugins
    elif [[ $function == Themes ]]; then
      _themes
    elif [[ $function == Exit ]]; then
      exit 0
    fi
}

function _plugins() {
  function=$(whiptail --title "rtx" --menu "Choose an option:" --ok-button "Continue" --nocancel 12 50 4 \
               Install "plugins" \
               Remove "plugins" \
               Back "" \
               Exit "" 3>&1 1>&2 2>&3)

    if [[ $function == Install ]]; then
      _itplugs
    elif [[ $function == Remove ]]; then
      _rmplugs
    elif [[ $function == Back ]]; then
      _function
    elif [[ $function == Exit ]]; then
      exit 0
    fi
}

function _themes() {
  function=$(whiptail --title "rtx" --menu "Choose an option:" --ok-button "Continue" --nocancel 12 50 4 \
               Install "themes" \
               Remove "themes" \
               Back "" \
               Exit "" 3>&1 1>&2 2>&3)

    if [[ $function == Install ]]; then
      _itthemes
    elif [[ $function == Remove ]]; then
      _rmthemes
    elif [[ $function == Back ]]; then
      _function
    elif [[ $function == Exit ]]; then
      exit 0
    fi
}

function _itplugs() {
  installa=()
  plugs=(_getdir _noty _noty2 _task autotools check_port chunks cookies cpuload create data datadir diskspace edit erasedata extratio extsearch feeds filedrop filemanager fileshare geoip history httprpc ipad loginmgr logoff lookat mediainfo mobile pausewebui ratio ratiocolor retrackers rpc rss rssurlrewrite rutracker_check scheduler screenshots seedingtime show_peers_like_wtorrent source spectrogram theme throttle tracklabels trafic unpack uploadeta xmpp)
  for i in "${plugs[@]}"; do
    plug=${i}
    if [[ ! -d /srv/rutorrent/plugins/${plug} ]]; then
      installa+=("$i" '""')
    fi
  done
  whiptail --title "Choose Plugins" --checklist --noitem --separate-output "Make some choices:" 15 46 7 "${installa[@]}" 2>/tmp/results
  
  exitstatus=$?
  if [[ $exitstatus = "1" ]]; then
    _plugins
  fi

  readarray result < /tmp/results
  for i in "${result[@]}"; do
    result=$(echo $i)
    echo -e "Installing ${result}"
    cd /srv/rutorrent/plugins
    case "$result" in
        _getdir|_noty|_noty2|_task|autotools|check_port|chunks|cookies|cpuload|create|data|datadir|diskspace|edit|erasedata|extratio|extsearch|feeds|filedrop|geoip|history|httprpc|ipad|loginmgr|lookat|mediainfo|ratio|retrackers|rpc|rss|rssurlrewrite|rutracker_check|scheduler|screenshots|seedingtime|show_peers_like_wtorrent|source|spectrogram|theme|throttle|tracklabels|trafic|unpack|uploadeta|xmpp)
        if [[ $result = "ipad" ]]; then
            if [[ -d /srv/rutorrent/plugins/mobile ]]; then
                echo "iPad plugin is not compatible with mobile"
                continue
            fi
        fi

        git clone --depth=1 https://github.com/Novik/ruTorrent.git
        mv ruTorrent/plugins/${result} ${result}
        rm -rf ruTorrent

        if [[ $result = "create" ]]; then
            sed -i 's/useExternal = false;/useExternal = "mktorrent";/' /srv/rutorrent/plugins/create/conf.php
            sed -i 's/pathToCreatetorrent = '\'\''/pathToCreatetorrent = '\''\/usr\/bin\/mktorrent'\''/' /srv/rutorrent/plugins/create/conf.php
        elif [[ $result = "spectrogram" ]]; then
            apt-get -y -q install sox > /dev/null 2>&1
            sed -i "s/\$pathToExternals\['sox'\] = ''/\$pathToExternals\['sox'\] = '\/usr\/bin\/sox'/g" /srv/rutorrent/plugins/spectrogram/conf.php
        fi
        ;;
        filemanager)
        git clone https://github.com/nelu/rutorrent-filemanager /srv/rutorrent/plugins/filemanager >> /dev/null 2>&1
        ;;
        fileshare)

        git clone --depth=1 https://github.com/nelu/rutorrent-thirdparty-plugins.git >/dev/null 2>&1
        mv rutorrent-thirdparty-plugins/fileshare .
        rm -rf rutorrent-thirdparty-plugins

        ln -s /srv/rutorrent/plugins/fileshare/share.php /srv/fancyindex/share.php >/dev/null 2>&1
        sed -i 's/$downloadpath .*/$downloadpath = $_SERVER['"'HTTP_HOST'"'] . '"'\/fancyindex\/share.php'"';/g' /srv/rutorrent/plugins/fileshare/conf.php
        ;;
        #fileupload)
        #svn co https://github.com/nelu/rutorrent-thirdparty-plugins/trunk/fileupload >/dev/null 2>&1
        #;;
        logoff)
        wget -q https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/rutorrent-logoff/logoff-1.3.tar.gz
        tar xf logoff-1.3.tar.gz >/dev/null 2>&1
        rm -rf logoff-1.3.tar.gz
        ;;
        mobile)
        git clone https://github.com/ajvulcan/rutorrentMobile.git mobile >/dev/null 2>&1
        rm -r /srv/rutorrent/plugins/ipad
        ;;
        pausewebui)
        git clone https://github.com/Gyran/rutorrent-pausewebui.git pausewebui >/dev/null 2>&1
        ;;
        ratiocolor)
        
        git clone --depth=1 https://github.com/Gyran/rutorrent-ratiocolor.git >/dev/null 2>&1
        mv rutorrent-ratiocolor ratiocolor
        rm -rf rutorrent-ratiocolor

        sed -i "s/changeWhat = \"cell-background\";/changeWhat = \"font\";/g" /srv/rutorrent/plugins/ratiocolor/init.js
        ;;
    esac
    done
    chown -R www-data: /srv/rutorrent/plugins
    /usr/local/bin/swizzin/php-fpm-cli -r 'opcache_reset();'
    rm /tmp/results
    _function
}

function _rmplugs() {
  removea=()
  plugs=(autotools checkport chunks cookies cpuload create data datadir diskspace edit erasedata extratio extsearch feeds filedrop filemanager fileshare fileupload geoip getdir history httprpc ipad loginmgr logoff lookat mediainfo mobile noty pausewebui ratio ratiocolor retrackers rpc rss rssurlrewrite rutracker_check scheduler screenshots seedingtime show_peers_like_wtorrent source spectrogram task theme throttle tracklabels trafic unpack uploadeta xmpp)
  for i in "${plugs[@]}"; do
    plug=${i}
    if [[ -d /srv/rutorrent/plugins/$i ]]; then
      removea+=("$i" '""')
    fi
  done
  whiptail --title "Choose Plugins" --noitem --checklist --separate-output "Make some choices:" 15 46 7 "${removea[@]}" 2>/tmp/results

  exitstatus=$?
  if [[ $exitstatus = "1" ]]; then
    _plugins
  fi

    readarray result < /tmp/results
    for i in "${result[@]}"; do
      result=$(echo $i)
      echo -e "Removing ${result}"
      rm -rf /srv/rutorrent/plugins/${result}
      if [[ $result = "fileshare" ]]; then
          rm -f /srv/fancyindex/share.php
      fi
    done
  /usr/local/bin/swizzin/php-fpm-cli -r 'opcache_reset();'
  rm /tmp/results
  _function
}

function _itthemes() {
  installa=()
  themes=(Acid Agent34 Agent46 Blue club-QuickBox Dark DarkBetter Excel FlatUI_Dark FlatUI_Light FlatUI_Material MaterialDesign Oblivion OblivionBlue rtModern-Remix)
  for i in "${themes[@]}"; do
    plug=${i}
    if [[ ! -d /srv/rutorrent/plugins/theme/themes/${i} ]]; then
      installa+=("$i" '""')
    fi
  done
  whiptail --title "Choose Themes" --checklist --noitem --separate-output "Make some choices:" 15 46 7 "${installa[@]}" 2>/tmp/results
  
  exitstatus=$?
  if [[ $exitstatus = "1" ]]; then
    _themes
  fi

  readarray result < /tmp/results
  for i in "${result[@]}"; do
    result=$(echo $i)
    echo -e "Installing ${result}"
    cd /srv/rutorrent/plugins/theme/themes

    case "$result" in
        Acid|Blue|Dark|Excel|Oblivion)
        git clone https://github.com/Novik/ruTorrent.git ${result} >/dev/null 2>&1
        ;;
        Agent*|OblivionBlue)
        git clone https://github.com/ArtyumX/ruTorrent-Themes.git ${result} >/dev/null 2>&1
        ;;
        DarkBetter)
        git clone https://github.com/chocolatkey/DarkBetter.git ${result} >/dev/null 2>&1
        ;;
        club-QuickBox)
        git clone https://github.com/QuickBox/club-QuickBox.git ${result} >/dev/null 2>&1
        ;;
        FlatUI*)
        git clone https://github.com/exetico/FlatUI.git ${result} >/dev/null 2>&1
        ;;
        MaterialDesign)
        git clone https://github.com/phlooo/ruTorrent-MaterialDesign.git ${result} >/dev/null 2>&1
        ;;
        rtModern-Remix)
        git clone https://github.com/ajvulcan/rtModern-Remix.git ${result} >/dev/null 2>&1
        ;;
    esac

    done
    chown -R www-data: /srv/rutorrent/plugins
    /usr/local/bin/swizzin/php-fpm-cli -r 'opcache_reset();'
    rm /tmp/results
    _function
}

function _rmthemes() {
  removea=()
  themes=(Acid Agent34 Agent46 Blue club-QuickBox Dark Excel FlatUI_Dark FlatUI_Light FlatUI_Material MaterialDesign Oblivion OblivionBlue rtModern-Remix)
  for i in "${themes[@]}"; do
    themes=${i}
    if [[ -d /srv/rutorrent/plugins/theme/themes/$i ]]; then
      removea+=("$i" '""')
    fi
  done
  whiptail --title "Choose Themes" --noitem --checklist --separate-output "Make some choices:" 15 46 7 "${removea[@]}" 2>/tmp/results

  exitstatus=$?
  if [[ $exitstatus = "1" ]]; then
    _themes
  fi

    readarray result < /tmp/results
    for i in "${result[@]}"; do
      result=$(echo $i)
      echo -e "Removing ${result}"
      rm -rf /srv/rutorrent/plugins/theme/themes/${result}
    done
  /usr/local/bin/swizzin/php-fpm-cli -r 'opcache_reset();'
  rm /tmp/results
  _function
}

_intro
_function
