#!/bin/bash
# SERVIDOR HD Quota Set Script

function _setdisk() {
username="$1"
SIZE="$2"
if [[ -z $1 ]]; then 
  echo "======================================================================================"
  echo "El espacio de disco debe estar en MB/GB/TB or max - NO añada decimales en la configuracion de espacio,"
  echo "Ejemplo - BIEN: 711GB, 2TB,, o max"
  echo "Ejemplo - MAL: 711.5GB, 2.5TB, o MAX"
  echo "Puedes usar setdisk username size para poner valores de forma no interactiva"
  echo "Ejemplo - 'setdisk myuser 20GB'"
  echo "======================================================================================"
  echo
fi
if [[ -z $username ]]; then
    echo -n "Nombre de usuario: "
    read -r username
  else 
    if [[ ! $(id -u "$username") ]]; then
      echo "el usuario no existe. Saliendo"
      return 1
    fi
fi
if [[ -z "$SIZE" ]]; then
  echo "Tamaño de cuota para el user: (Ej: 500GB, 2TB, max): "
  read -r SIZE
fi

if [[ $SIZE = 'max' ]]; then 
  echo "Usando el tamaño max. Observe que este es más del que está actualmente en disco disponible."
elif echo "$SIZE" | grep -q -E '^[0-9]+(M|T|G)B$'; then
  # echo "Using $SIZE" 
  :
else
  SIZE='Invalid'
fi

case "$SIZE" in
  max)
    fstabid=$(grep quota /etc/fstab | awk '{printf $1}')
    if [[ $fstabid =~ "UUID" ]]; then
      uuid=$(echo "$fstabid" | cut -d= -f 2)
      disk=$(blkid -U "$uuid")
    elif [[ $fstabid =~ "LABEL" ]]; then
      label=$(echo "$fstabid" | cut -d= -f 2)
      disk=$(blkid -L "$label")
    else
      disk=$fstabid
    fi

    onekblocks=$(df "$disk" --output=source,size | tail -1 | awk '{printf $2}')
    humansize=$(df "$disk" -h --output=source,size | tail -1 | awk '{printf $2}')
    echo "Maximum on $disk is $onekblocks (approx $humansize)"

    # setquota -u "${username}" "$onekblocks" "$onekblocks" 0 0 -a
  ;;
  *TB)
    QUOTASIZE=$(echo "$SIZE"|cut -d'T' -f1)
    DISKSIZE=$((QUOTASIZE * 1024 * 1024 * 1024))
    setquota -u "${username}" "${DISKSIZE}" "${DISKSIZE}" 0 0 -a
  ;;
  *GB)
    QUOTASIZE=$(echo "$SIZE"|cut -d'G' -f1)
    DISKSIZE=$((QUOTASIZE * 1024 * 1024))
    setquota -u "${username}" "${DISKSIZE}" "${DISKSIZE}" 0 0 -a
  ;;
  *MB)
    QUOTASIZE=$(echo "$SIZE"|cut -d'M' -f1)
                DISKSIZE=$((QUOTASIZE * 1024))
                setquota -u "${username}" "${DISKSIZE}" "${DISKSIZE}" 0 0 -a
  ;;
  *)
    echo "================================================================"
    echo "El tamaño de error de cuota tiene que estar en 'max' o entero de MB/GB/TB."
    echo "Escribe 'setdisk $1' y prueba de nuevo"
    echo "================================================================";return 1
  ;;
esac
}

if [[ -f /install/.quota.lock ]]; then
  _setdisk "$1" "$2"
else
  echo "Quota no instalada"
  return 1
fi
